config/routes.rb
Spree::Core::Engine.routes.append do
  # Add your extension routes here
	root :to => 'home#index'
	match '/admin/store_details'=>'admin/store_details#index'
	match '/admin/store_details/billing_history'=>'admin/store_details#billing_history'
	match '/admin/store_details/store_billing'=>'admin/store_details#store_billing'
	match '/admin/owners'=>'admin/users#index',:as =>:admin_store_owners
	match 'store/:id' => 'stores_registration#new_store'
	match 'store' => 'stores_registration#save_store_details'
	match '/user/password/reset_password' => 'password#reset_password'
	match '/user/password/reset' => 'password#reset_password_data'
	match '/storeowner' => 'stores_registration#storeowner',:as=>:storeowner
	match 'user_update_plan/:plan_id'=>'admin/upgrade_plans#user_update_plan',:as=>:update_plan
	match 'admin/store_registration_payment_method'=>'admin/payment_methods#store_registration_payment_method',:as=>:store_registration_payment_method
	match '/admin/users/store_status'=>'admin/users#store_owners'
	 match '/static_pages/aboutus' => 'static_pages#aboutus'
        match '/static_pages/contactus' => 'static_pages#contactus'
        match '/static_pages/privacy' => 'static_pages#privacy'
       match '/static_pages/terms' => 'static_pages#terms'
	namespace :admin do
		resources :pricing_plans
		resources :domain_customizes
		resources :upgrade_plans
	end
	resources :stores_registration
end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/address_decorator.rb
include Geokit::Geocoders
Spree::Address.class_eval do
  validate :request_state_and_city_validation_based_on_zipcode, :if => :zipcode
  private
  def request_state_and_city_validation_based_on_zipcode
    poll = true # default true for new objects
    if poll
      loc = MultiGeocoder.geocode("#{self.zipcode},#{find_country_code}")
    end # Add Validation Error if location is not found
    unless loc.success
      errors.add(:zipcode, " Unable to geocode your location from zipcode entered.")
    else # Validate state and city fields in compare to loc object returned by geocode
      errors.add(:country,"doesn't matches with zipcode entered") if find_country_code!=loc.country_code
      errors.add(:state, "doesn't matches with zipcode entered") if find_state_code != loc.state
      errors.add(:city, "doesn't matches with zipcode entered") if self.city != loc.city
	  end
  end
  def find_country_code
    self.country.id
    Spree::Country.find_by_name(self.country)
    Spree::Country.find_by_id(self.country.id).iso if Spree::Country.find_by_name(self.country)
  end
  def find_state_code
    Spree::State.find_by_id(self.state.id).abbr if  Spree::State.find_by_id(self.state)
  end
end

app/models/spree/billing_history.rb
module Spree
  class BillingHistory < ActiveRecord::Base
		attr_accessible :type,:store_owner_id,:amount,:billing_date,:transaction_id,:acknowledge,:payment_type,:message
		belongs_to :store_owner
  end
end

app/models/spree/domain_customize.rb
module Spree
  class DomainCustomize < ActiveRecord::Base
    attr_accessible :custom_domain, :status
		belongs_to :store_owner
		validates :custom_domain, :presence => true,:uniqueness => true, :allow_blank=>true,:format =>{:with => /\A([^.\s]+).((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  end
end

app/models/spree/inventory_unit_decorator.rb
Spree::InventoryUnit.class_eval do
  attr_accessible :variant, :state, :shipment
  def self.create_units(order, variant, sold, back_order)
  	domain=Spree::Product.find_by_id(variant.product_id).domain_url
		config=Spree::Configuration.find_by_name("Default configuration")
		pref=Spree::Preference.where("domain_url=? AND owner_type=?",domain,"Configuration")
		if  pref.blank?
			back_order_val=Spree::Config[:allow_backorders]
		else
			back_order_val=pref.select{|x|x.name=="allow_backorders"}.map(&:value)[0]
		end
		if back_order > 0 && !back_order_val
      raise "Cannot request back orders when backordering is disabled"
    end
    shipment = order.shipments.detect {|shipment| !shipment.shipped? }
    sold.times { order.inventory_units.create(:variant => variant, :state => "sold", :shipment => shipment) }
    back_order.times { order.inventory_units.create(:variant => variant, :state => "backordered", :shipment => shipment) }
  end

end

app/models/spree/mail_method_decorator.rb
Spree::MailMethod.class_eval do
  attr_accessible :domain_url
  def self.current(domain=nil,id=nil)
    if domain==nil
      return nil
    elsif domain=="domain" && id=="interceptor"
      return @mail
    else
      @mail= Spree::MailMethod.where("environment=? AND domain_url=?",Rails.env,domain).first
      return @mail
    end
  end
end

app/models/spree/option_types_decorator.rb
Spree::OptionType.class_eval do
  attr_accessible :domain_url
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
  attr_accessible :domain_url
  attr_accessible :store_owner_id, :order_id, :is_custom
  def available_shipping_methods(display_on = nil)
    return [] unless ship_address
    Spree::ShippingMethod.all_available(self, display_on,find_order_domain)
  end

  def find_order_domain
    domain=self.products.first.domain_url
    return domain
  end

  def available_payment_methods
    @available_payment_methods||= Spree::PaymentMethod.where("domain_url=?",find_order_domain).available(:front_end)
  end

  def payment_method
    if payment and payment.payment_method
      payment.payment_method
    else
      available_payment_methods.first
    end
  end
end

app/models/spree/payment_method_decorator.rb
Spree::PaymentMethod.class_eval do
  attr_accessible :type,:domain_url
end

app/models/spree/preference_decorator.rb
Spree::Preference.class_eval do
	attr_accessible:owner_type, :domain_url
end

app/models/spree/pricing_plan.rb
module Spree
  class PricingPlan < ActiveRecord::Base
		belongs_to :store_owner
		validates :plan_name, :presence => true,:uniqueness => true, :format => { :with => /^[A-Za-z ]+$/ },:allow_blank=>true
		validates :no_of_products, :presence=> true,:allow_blank=> true,:numericality=> {:only_integer=> true ,:greater_than=> 0}
		validates :amount, :presence => true,:numericality => {:greater_than => 0},:allow_blank=>true
		attr_accessible :plan_name,:amount,:no_of_products,:is_active,:transaction_fee,:payment_period

  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  attr_accessible :domain_url
end

app/models/spree/promotion_decorator.rb
Spree::Promotion.class_eval do
	attr_accessible :domain_url
  #Overriding eligible? method to identify the domain
  def eligible?(order)
		if order
			store=StoreownerOrder.find_by_order_id(order.id).store_owner
			if self.domain_url == store.domain
				!expired? && rules_are_eligible?(order)
			else
				return false
			end
		end
  end

end

app/models/spree/properties_decorator.rb
Spree::Property.class_eval do
  attr_accessible :domain_url
end

app/models/spree/prototypes_decorator.rb
Spree::Prototype.class_eval do
  attr_accessible :domain_url
end

app/models/spree/shipping_category_decorator.rb
Spree::ShippingCategory.class_eval do
  attr_accessible :domain_url
end

app/models/spree/shipping_method_decorator.rb
Spree::ShippingMethod.class_eval do
  attr_accessible :domain_url
  def self.all_available(order, display_on=nil, domain=nil)
    ship_domain=Spree::ShippingMethod.where(:domain_url=>domain)
    ship_domain.select { |method| method.available_to_order?(order,display_on)}
  end

end

app/models/spree/store_detail.rb
module Spree
  class StoreDetail < ActiveRecord::Base
    attr_accessible :product_id, :quantity, :domain_url
		def self.store_details
			owners=StoreOwner.all
			owners.each do |owner|
				transaction_fee_amount=find_transaction_fee(owner)
				pricing_amount= pricing_plan_amount(owner)
				total_amounts=total_amount(transaction_fee_amount,pricing_amount)
				store_credit_details=credit_card(owner)
				store_bill_details=billing_address(owner)
				capture_amount=payment_response(owner,total_amounts,store_credit_details,store_bill_details)
			end
		end


		def self.find_transaction_fee(owner)
			price=owner.pricing_plan
			if owner && !owner.domain.blank?
        products=StoreDetail.where("domain_url=?",owner.domain).map(&:product_id).uniq
				if products && !products.empty?
					final_price=0
					products.each do |product|
						pro_quantity=StoreDetail.find_all_by_product_id(product).map(&:quantity).sum
						pro_id=Product.find_by_id(product)
						total_price=(pro_id.master.price*(price/100))*pro_quantity
						final_price=final_price+total_price
					end
				else
					final_price=0
				end
			  return final_price
		  end
		end

		def self.pricing_plan_transact_fee(owner)
			transaction_fee=owner.pricing_plan.transaction_fee
		end

		def self.pricing_plan_amount(owner)
			amount=owner.pricing_plan.amount
		end

		def self.total_amount(transaction_fee_amount,pricing_amount)
			amount=transaction_fee_amount+pricing_amount
		end


		def self.credit_card(owner)
			ActiveMerchant::Billing::CreditCard.new(
				:number =>owner.card_number,
				:type =>owner.card_type,
				:first_name =>owner.first_name,
				:last_name =>owner.last_name,
				:month => owner.expiration_month,
				:year =>owner.expiration_year,
				:verification_value =>owner.cvv
			)
		end

		def self.billing_address(owner)
			address=Hash.new
			address={ :name =>owner.name,
				:address1 =>owner.address1,
				:address2 =>owner.address2,
				:city =>owner.city,
				:state =>owner.state,
				:country =>owner.country,
				:zip =>owner.zipcode,
				:phone =>owner.phoneno}
		end


		def self.paypal_gateway
			gateway = ActiveMerchant::Billing::PaypalGateway.new(:login =>APP_CONFIG['paypal_username'],:password =>APP_CONFIG['paypal_password'],:signature =>APP_CONFIG['paypal_signature'])
			return gateway
		end

		def self.payment_response(owner,total_amounts,store_credit_details,store_bill_details)
			authorize= paypal_gateway.authorize(total_amounts, store_credit_details,
        :ip => owner.ip,
        :billing_address =>store_bill_details
			)
			if authorize.params['ack']=="Success"
				response=paypal_gateway.capture(total_amounts, authorize.authorization)
				transaction_id=response.params['transaction_id']
				type="capture"
				acknowledge=response.params['ack']
				if acknowledge=="Success"
					update_billing(owner,transaction_id,type,acknowledge,total_amounts)
				else
					update_billing(owner,transaction_id,type,acknowledge,total_amounts)
					de_active(owner)
				end
			else
				transaction_id=0
				type="authorize"
				acknowledge=authorize.params['ack']
				update_billing(owner,transaction_id,type,acknowledge,total_amounts)
				de_active(owner)
			end
		end

		def self.de_active(owner)
			store=StoreOwner.find_by_id(owner.id)
			store.update_attribute(:is_active,false)
		end

		def self.update_billing(owner,transaction_id,type,acknowledge,total_amounts)
			billing_details=BillingHistory.create!(:store_owner_id=>owner.id,:amount=>total_amounts,:billing_date=>Date.today,:transaction_id=>transaction_id,:acknowledge=>acknowledge,:payment_type=>type)
		end

  end
end

app/models/spree/store_owner.rb
include Geokit::Geocoders
module Spree
  class StoreOwner < ActiveRecord::Base
		has_one :domain_customize
		has_one :pricing_plan
		has_many :storeowner_orders
		has_many :transactions
		has_many :billing_histories
		belongs_to :user
		belongs_to :pricing_plan
		attr_accessible :first_name,:last_name,:card_number,:cvv,:card_type,:domain,:phoneno,:name,:address1,:address2,:city,:card_number,:zipcode,:country, :state, :expiration_year, :expiration_month
		validates :first_name, :presence => {:message=>"First name cant be blank"},:format => { :with => /^[A-Za-z ]+$/ ,:message => "Please enter a valid name "},:allow_blank=>true
		validates :name, :presence => {:message=>"First name cant be blank"},:format => { :with => /^[A-Za-z ]+$/ ,:message => "Please enter a valid name "},:allow_blank=>true
		validates :last_name, :presence =>  {:message=>"Last name cant be blank"},:format => { :with => /^[A-Za-z ]+$/ ,:message => "Please enter a valid name"},:allow_blank=>true
		validates :card_number,:presence =>{:message => "Please enter a card number"},:allow_blank => true
		validates :cvv,:presence =>{:message => "Please enter a CVV code"},:format => { :with => /^[0-9]+$/,:message => "Please enter a valid CVV code"},:allow_blank=>true
		validates :card_type ,:presence =>{:message => "Please enter a card type"},:allow_blank => true
		validates :domain ,:presence =>{:message => "Please enter a domain name"},:uniqueness=>true,:format => { :with => /^[A-Za-z]+$/ },:allow_blank => true
		validates :phoneno,:presence =>{:message => "Please enter a phone no"},:numericality => { :message=>"please enter a valid phoneno"},:length => { :is => 10,	:message => " number is not valid " },:allow_blank => true
		validates :name,:presence =>{:message => "Please enter a name"},:allow_blank => true
		validates :address1, :presence => {:message=>"Please enter a  Address 1"}
		validates :address2, :presence => {:message=>"Please enter a Address 2"}
		validates :city, :presence =>{:message=>"Please enter a city"},:format => { :with => /^[A-Za-z ]+$/ },:allow_blank=>true
		validates :card_number, :presence => {:message=>"please enter a card number"},:numericality => { :message=>"please enter a valid number"},:allow_blank=>true
		validates :cvv, :presence => {:message=>"please enter a cvv"},:numericality => { :message=>"please enter a valid cvv"},:allow_blank=>true
		validates :zipcode,:presence =>{:message=>"Please enter a Zip code"}
		validate :request_state_and_city_validation_based_on_zipcode, :if => :zipcode
		#~ validates_credit_card :card_number, :card_type,:allow_blank => true

    def request_state_and_city_validation_based_on_zipcode
      poll = true # default true for new objects
      if poll
        loc = MultiGeocoder.geocode("#{self.zipcode},#{find_country_code}")
      end # Add Validation Error if location is not found
      unless loc.success
        errors.add(:zipcode, " Unable to geocode your location from zipcode entered.")
      else # Validate state and city fields in compare to loc object returned by geocode
        errors.add(:country,"Country doesn't matches with zipcode entered") if find_country_code!=loc.country_code
        errors.add(:state, "State doesn't matches with zipcode entered") if find_state_code != loc.state
        errors.add(:city, "City doesn't matches with zipcode entered") if self.city != loc.city
      end
    end
  end
end

def find_country_code
  Spree::Country.find_by_name(self.country).iso
end

def find_state_code
  Spree::State.find_by_name(self.state).abbr
end

app/models/spree/store_reg_payment_method.rb
module Spree
  class StoreRegPaymentMethod < ActiveRecord::Base
    attr_accessible :password,:username,:signature
		validates :username, :presence =>true,:allow_blank=>true
		validates :password, :presence =>true,:allow_blank=>true
		validates :signature, :presence =>true,:allow_blank=>true
  end
end

app/views/spree/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head data-hook="admin_inside_head">
  <%= render :partial => 'spree/admin/shared/head' %>
</head>
<body class='admin' data-ajax-root-path="<%= spree.root_path %>">
<!--[if IE 7]>
<div id='IE7'>
<![endif]-->
<div id='wrapper' data-hook>

  <div id="header" data-hook>

    <div data-hook="admin_login_navigation_bar"></div>

    <%= link_to image_tag(Spree::Config[:admin_interface_logo], :id => 'logo'), spree.admin_path %>
    <h1><%= link_to t(:administration), spree.admin_path %></h1>
    <div id="progress"><%= image_tag 'admin/progress.gif' %> <%= t(:loading) %>...</div>
  </div>

  <div id="admin-menu" data-hook>
    <ul data-hook="admin_tabs">
      <%= render :partial => 'spree/admin/shared/tabs' %>
    </ul>
    <br class="clear" />
  </div>

  <div id="sub-menu" data-hook>
    <%= yield :sub_menu %>
    <br class="clear" />
  </div>

  <div class="<%= 'with-sidebar ' if content_for?(:sidebar) %> clear tile_bg" id="content" data-hook>

    <% if flash[:error] %>
      <div class="flash error"><%= flash[:error] %></div>
    <% end %>
    <% if notice %>
      <div class="flash notice"><%= notice %></div>
    <% end %>

    <%= render :partial => 'spree/admin/shared/alert', :collection => session[:alerts] %>

    <%= yield %>

    <% if content_for?(:sidebar) %>
      <br class="clear" />
      <div id="sidebar" data-hook>
        <%= yield :sidebar %>
      </div>
    <% end %>

  </div>

  <div id="footer" data-hook>
    <p><%= t(:icons_by) %> <%= link_to 'pInvoke', 'http://pinvoke.com' %></p>
  </div>


</div>
<!--[if IE]>
</div>
<![endif]-->

<div data-hook="admin_footer_scripts"></div>
</body>
</html>

app/views/spree/layouts/home.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <head data-hook="inside_head">
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<%= csrf_meta_tag %>
<%#= javascript_include_tag 'jquery-1.4.2.min', 'jquery.validate.min.js', 'rails', 'application', :cache => 'jquery-core' %>
<% unless I18n.locale.to_s[0..1] == 'en' %>
  <%#= javascript_include_tag ['localization/messages_', I18n.locale.to_s[0..1], '.js'].join %>
<% end %>
<%= yield :head %>

<link rel="stylesheet" href="/assets/style_new.css" type="text/css" />
</head>
<body>
		<div class="wrapper">			
			<div class="mainwrapper">
				<div class="header">
					<div class="logo">
						<h1>
							<a href="/">Home</a>
						</h1>
					</div>
					<div class="tophead">
						<div class="topsection">
							<div class="global-nav">
								<ul>
									<li><a href="/">Home</a></li>
									<li><a href="/static_pages/terms">Terms &amp; Conditions</a></li>
									<li><a href="/static_pages/aboutus">About us</a></li>
								</ul>
							</div>
							<div class="cartinfo">
								<ul>
									<li class="login"><a href="/login"> Log In </a></li>
								</ul>
							</div>
						</div>
					</div>
				</div><!-- header -->
				<div class="body-container clearfix">
					<div class="login-container">											
						<div class="loginbox">
						  <% if flash.notice %>
      <div class="flash notice"><div class="errorwrapper">
<ul><li><%= flash.notice %></li></ul></div></div>
      <% end %>
      <% if flash[:error] %>
      <div class="flash errors">
				<div class="errorwrapper">
					<ul><li><%= flash[:error] %></li></ul>
				</div>
			</div>
      <% end %>
							<%=yield%>
						</div>
					</div>
				</div><!-- body container -->
                <div class="footer">
            		<p class="copy-rights">Copyright © <a href="http://www.railsfactory.org" target="_blank" >Railsfactory</a>. 2012. All Rights Reserved</p>
                    <ul>
                    	<li><a href="/">Home</a></li><li>|</li>
                        <li><a href="/static_pages/aboutus">About Us</a></li><li>|</li>
                        <li><a href="/static_pages/terms">Terms &amp; Conditions</a></li>
                    </ul>
            	</div>
			</div>
		</div>
	</body>
</html>

app/views/spree/layouts/saas.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Crux</title>
<!--<link href="/stylesheets/style.css" media="screen" rel="stylesheet" type="text/css" />-->
<%= stylesheet_link_tag 'style'%>

</head>
<body>
<div class="main-header">
<div class="logo">
<a href="/"><img alt="" src="/assets/logo-crux.png" /></a>
<!--<a href="#" style="margin-left:20px;"><img alt="" src="images/spree_50.png" /></a>-->
</div>
<!--<div class="top_navi">
<ul>
<li><a href="#">Login</a></li>
<li class="last"><a href="#">Home</a></li>
</ul>
</div>-->
<ul id="nav-primary">
<%c=controller.controller_name%>
<%if c=="home"%>
<li class="active"><a href="/">Home</a></li>
<%else%>
<li ><a href="/">Home</a></li>
<%end%>
<!--<li><a href="#">Feature Tour</a></li>
<li><a href="#">Examples</a></li>-->
<li><a href="#">FAQ</a></li>
<%if c=="stores_registration"%>
<li class="active"><a href=<%= stores_registration_index_path%>>Pricing &amp; Signup</a></li>
<%else%>
<li ><a href=<%= stores_registration_index_path%>>Pricing &amp; Signup</a></li>
<%end%>
</ul>
</div>
<%=yield%>
<div class="footer main-wrapper">
<p>Powered by <a href="http://www.railsfactory.org" target="_blank">Railsfactory</a></p>
<ul class="foo-menu">
<li><a href="/static_pages/terms">Terms &amp; Conditions</a></li>
<li><a href="/static_pages/privacy">Privacy Policy</a></li>
<li><a href="/static_pages/contactus">Contact</a></li>
</ul>        
</div>
</body>
</html>

app/views/spree/layouts/spree_application.html.erb
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
        <head>
  <head data-hook="inside_head">
    <%= render :partial => 'spree/shared/head' %>
  </head>
<%
if @body_class.nil?
if content_for?(:sidebar)
@body_class = 'two-col'
else
@body_class = 'one-col'
end
end
%>        
        <body class="<%= @body_class %>" id="<%= @body_id %>">
                <div class="wrapper">                        
                        <div class="mainwrapper">
                                <div class="header">
                                        <div class="logo">
                                                <h1>
                                                        <a href="/">Home</a>
                                                </h1>
                                        </div>
                                        <div class="tophead">
                                                <div class="topsection">
                                                        <div class="global-nav">
                                                                <ul>
                                                                        <li><a href="/">Home</a></li>
                                                                        <li><a href="/static_pages/terms">Terms &amp; Conditions</a></li>
                                                                        <li><a href="/static_pages/aboutus">About Us</a></li></li>
                                                                </ul>
                                                        </div>
                                                        <div class="cartinfo">
                                                                <ul>
            <%= render :partial => 'spree/shared/nav_bar' %>
                                                                </ul>
                                                        </div>
                                                </div>
                                                <div class="product-search">
          <%= render :partial => 'spree/shared/search' %>
                                                </div>
                                        </div>
                                </div><!-- header -->
                                <div class="body-container clearfix">
                                        <div class="asidepanel">
                                                <div class="sidenav">
                                                <% if content_for?(:sidebar) %>
          <aside id="sidebar" class="columns alpha four" data-hook>
                        <%= yield :sidebar %>
          </aside>
                        <% end %>
                                     
                                                </div><!-- sidenav -->
                                                <div class="promo-banner">
                                                
                                                        <img src="/assets/promo-banner.png" alt="" />
                                                </div>                                        
                                        </div>
                                        <div class="contpanel">                                                
                                                   <% if flash.notice %>
      <div class="flash notice">                                    <div class="errorwrapper">
<ul><li><%= flash.notice %></li></ul></div></div>
      <% end %>
      <% if flash[:error] %>
      <div class="flash errors">                                    <div class="errorwrapper">
<ul><li><%= flash[:error] %></li></ul></div></div>
      <% end %>
                                                <%=yield%>
                        <div class="brands">
                                                        <h4 class="sechead">LATEST COLLECTIONS</h4>
                                                        <div class="sroll-mid">
                                                                <div class="brand-list">
                                                                        <%products=find_latest_products%>
                                                                        <ul id="mycarousel" class="jcarousel-skin-tango">
                                                                 <%products.each do |product|%>
                                                                                <li><%= link_to small_image(product), product %></li>
                                                                        <%end%>
                                                                        </ul>
                                                                        <br><br>
                                                                </div>
                                                        </div>
                                                </div>
                                                <!-- brands -->

                                        </div>
                                </div><!-- body container -->
                <div class="footer">
                            <p class="copy-rights">Copyright &copy; 2012 <a href="http://www.railsfactory.org" target="_blank">Railsfactory</a>. All Rights Reserved</p>
                    <ul>
                            <li><a href="/">Home</a></li><li>|</li>
                        <li><a href="/static_pages/aboutus">About Us</a></li><li>|</li>
                        <li><a href="/static_pages/contactus">Contact Us</a></li><li>|</li>
                        <li><a href="/static_pages/privacy">Privacy</a></li><li>|</li>
                        <li><a href="/static_pages/terms">Terms &amp; Conditions</a></li>
                    </ul>
                    </div>
                        </div>
                </div>
        </body>
</html>
<script>
$('#mycarousel').jcarousel({
visible:4,
auto:1000
});
</script>

app/views/spree/layouts/static.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

<link rel="stylesheet" href="/assets/style_new.css" type="text/css" />

<body>
		<div class="wrapper">			
			<div class="mainwrapper">
				<div class="header">
					<div class="logo">
						<h1>
							<a href="/">Home</a>
						</h1>
					</div>
					<div class="tophead">
						<div class="topsection">
							<div class="global-nav">
							</div>
							<div class="cartinfo">
								<ul>
									<li class="login"><a href="/login"> Log In </a></li>
								</ul>
							</div>
						</div>
					</div>
				</div><!-- header -->
				<div class="body-container clearfix">
						  <% if flash.notice %>
      <div class="flash notice"><div class="errorwrapper">
<ul><li><%= flash.notice %></li></ul></div></div>
      <% end %>
      <% if flash[:error] %>
      <div class="flash errors">
				<div class="errorwrapper">
					<ul><li><%= flash[:error] %></li></ul>
      <% end %>
							<%=yield%>
						</div>
					</div>
				</div><!-- body container -->
                <div class="footer">
            		<p class="copy-rights">Copyright © <a href="http://www.railsfactory.com" target="_blank" >Railsfactory</a>. 2012. All Rights Reserved</p>
                    <ul>
                    	<li><a href="/">Home</a></li><li>|</li>
                        <li><a href="/static_pages/aboutus" >About Us</a></li><li>|</li>
												<li><a href="/static_pages/contactus">Contact Us</a></li><li>|</li>
                        <li><a href="/static_pages/privacy">Privacy</a></li><li>|</li>
                        <li><a href="/static_pages/terms">Terms &amp; Conditions</a></li>
                    </ul>
            	</div>
			</div>
		</div>
	</body>
</html>