config/routes.rb
Spree::Core::Engine.routes.append do
  # Add your extension routes here
	root :to => 'home#index'
	match '/admin/store_details'=>'admin/store_details#index'
	match '/admin/store_details/billing_history'=>'admin/store_details#billing_history'
	match '/admin/store_details/store_billing'=>'admin/store_details#store_billing'
	match '/admin/owners'=>'admin/users#index',:as =>:admin_store_owners
	match 'store/:id' => 'stores_registration#new_store'
	match 'store' => 'stores_registration#save_store_details'
	match '/user/password/reset_password' => 'password#reset_password'
	match '/user/password/reset' => 'password#reset_password_data'
	match '/storeowner' => 'stores_registration#storeowner',:as=>:storeowner
	match 'user_update_plan/:plan_id'=>'admin/upgrade_plans#user_update_plan',:as=>:update_plan
	match 'admin/store_registration_payment_method'=>'admin/payment_methods#store_registration_payment_method',:as=>:store_registration_payment_method
	match '/admin/users/store_status'=>'admin/users#store_owners'
	 match '/static_pages/aboutus' => 'static_pages#aboutus'
        match '/static_pages/contactus' => 'static_pages#contactus'
        match '/static_pages/privacy' => 'static_pages#privacy'
       match '/static_pages/terms' => 'static_pages#terms'
	namespace :admin do
		resources :pricing_plans
		resources :domain_customizes
		resources :upgrade_plans
	end
	resources :stores_registration
end

app/views/spree/admin/configurations/index.html.erb
<h1><%= t("configurations") %></h1>

<table class="index" data-hook="configuration">
  <thead>
    <tr>
      <th><%= t("system") %></th>
      <th><%= t("description") %></th>
    </tr>
  </thead>
 <tbody data-hook="admin_configurations_menu"  >
    
		  <% if current_user.has_role? "admin"%>
    <tr>
      <td><%= link_to t("general_settings"), admin_general_settings_path %></td>
      <td><%= t("general_settings_description") %></td>
    </tr>
    <tr>
      <td><%= link_to t("mail_methods"), admin_mail_methods_path %></td>
      <td><%= t("email_server_settings_description") %></td>
    </tr>
 <tr>
     <td><%= link_to t("store_registration_payment_method"), store_registration_payment_method_path %></td>
      <td>Payment Method for Store registration</td>
    </tr>

		<%end%>
		  <% unless current_user.has_role? "admin"%>
       <tr>
      <td><%= link_to t("domain_customizes"), admin_domain_customizes_path %></td>
      <td><%= t("domain_customization") %></td>
    </tr>
    <tr>
      <td><%= link_to t("mail_methods"), admin_mail_methods_path %></td>
      <td><%= t("email_server_settings_description") %></td>
    </tr>

    <tr>
      <td><%= link_to t("tax_categories"), admin_tax_categories_path %></td>
      <td><%= t("tax_categories_setting_description") %></td>
    </tr>
    <tr>
      <td><%= link_to t("zones"), admin_zones_path %></td>
      <td><%= t("zone_setting_description") %></td>
    </tr>
			<%end%>

    <tr>
      <td><%= link_to t("states"), admin_country_states_path(Spree::Config[:default_country_id]) %></td>
      <td><%= t("state_setting_description") %></td>
    </tr>
		  <% unless current_user.has_role? "admin"%>
    <tr>
      <td><%= link_to t("payment_methods"), admin_payment_methods_path %></td>
      <td><%= t("payment_methods_setting_description") %></td>
    </tr>

    <tr>
      <td><%= link_to t("taxonomies"), admin_taxonomies_path %></td>
      <td><%= t("taxonomies_setting_description") %></td>
    </tr>
    <tr>
      <td><%= link_to t("shipping_methods"), admin_shipping_methods_path %></td>
      <td><%= t("shipping_methods_description") %></td>
    </tr>
    <tr>
      <td><%= link_to t("shipping_categories"), admin_shipping_categories_path %></td>
      <td><%= t("shipping_categories_description") %></td>
    </tr>
    <tr>
      <td><%= link_to t("inventory_settings"), admin_inventory_settings_path %></td>
      <td><%= t("inventory_setting_description") %></td>
    </tr>
    <tr>
      <td><%= link_to t("tax_rates"), admin_tax_rates_path %></td>
      <td><%= t("tax_rates_description") %></td>
    </tr>
    <tr>
      <td><%= link_to t("tax_settings"), admin_tax_settings_path %></td>
      <td><%= t("tax_settings_description") %></td>
    </tr>
			<%end%>

    <tr>
      <td><%= link_to t("analytics_trackers"), admin_trackers_path %></td>
      <td><%= t("google_analytics_setting_description") %></td>
    </tr>
 			
  </tbody>
</table>