config/routes.rb
Spree::Core::Engine.routes.append do
  # Add your extension routes here
	root :to => 'home#index'
	match '/admin/store_details'=>'admin/store_details#index'
	match '/admin/store_details/billing_history'=>'admin/store_details#billing_history'
	match '/admin/store_details/store_billing'=>'admin/store_details#store_billing'
	match '/admin/owners'=>'admin/users#index',:as =>:admin_store_owners
	match 'store/:id' => 'stores_registration#new_store'
	match 'store' => 'stores_registration#save_store_details'
	match '/user/password/reset_password' => 'password#reset_password'
	match '/user/password/reset' => 'password#reset_password_data'
	match '/storeowner' => 'stores_registration#storeowner',:as=>:storeowner
	match 'user_update_plan/:plan_id'=>'admin/upgrade_plans#user_update_plan',:as=>:update_plan
	match 'admin/store_registration_payment_method'=>'admin/payment_methods#store_registration_payment_method',:as=>:store_registration_payment_method
	match '/admin/users/store_status'=>'admin/users#store_owners'
	 match '/static_pages/aboutus' => 'static_pages#aboutus'
        match '/static_pages/contactus' => 'static_pages#contactus'
        match '/static_pages/privacy' => 'static_pages#privacy'
       match '/static_pages/terms' => 'static_pages#terms'
	namespace :admin do
		resources :pricing_plans
		resources :domain_customizes
		resources :upgrade_plans
	end
	resources :stores_registration
end

app/models/spree/pricing_plan.rb
module Spree
  class PricingPlan < ActiveRecord::Base
		belongs_to :store_owner
		validates :plan_name, :presence => true,:uniqueness => true, :format => { :with => /^[A-Za-z ]+$/ },:allow_blank=>true
		validates :no_of_products, :presence=> true,:allow_blank=> true,:numericality=> {:only_integer=> true ,:greater_than=> 0}
		validates :amount, :presence => true,:numericality => {:greater_than => 0},:allow_blank=>true
		attr_accessible :plan_name,:amount,:no_of_products,:is_active,:transaction_fee,:payment_period

  end
end

app/controllers/spree/admin/pricing_plans_controller.rb
class Spree::Admin::PricingPlansController < Spree::Admin::ResourceController
  # GET /pricing_plans
  # GET /pricing_plans.xml
  #~ resource_controller
  before_filter :find_pricing_plan, :only => [:show,:edit,:update,:destroy]

  def index
    @search =Spree::PricingPlan.ransack(params[:search])
    #~ @pricing_plans = @search#.all.paginate(:per_page => Spree::Config[:admin_products_per_page], :page => params[:page])
    a=@search.object
    @pricing_plans = a

    #~ p @pricing_plans
    #~ p @pricing_plans.object
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pricing_plans }
    end
  end

  # GET /pricing_plans/1
  # GET /pricing_plans/1.xml

  def show
    find_pricing_plan
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pricing_plan }
    end
  end

  # GET /pricing_plans/new
  # GET /pricing_plans/new.xml

  def new
    @pricing_plan =Spree::PricingPlan.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pricing_plan }
    end
  end

  # GET /pricing_plans/1/edit

  def edit
    find_pricing_plan
  end

  # POST /pricing_plans
  # POST /pricing_plans.xml

  def create
    @pricing_plan = Spree::PricingPlan.new(params[:pricing_plan])
    respond_to do |format|
      if @pricing_plan.save
        format.html { redirect_to(admin_pricing_plan_path(@pricing_plan), :notice => 'Pricing plan was successfully created.') }
        format.xml  { render :xml => @pricing_plan, :status => :created, :location => @pricing_plan }
      else
        format.html { render  "new" }
        format.xml  { render :xml => @pricing_plan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pricing_plans/1
  # PUT /pricing_plans/1.xml

  def update
    find_pricing_plan
    respond_to do |format|
      if @pricing_plan.update_attributes(params[:pricing_plan])
        format.html { redirect_to(admin_pricing_plan_path(@pricing_plan), :notice => 'Pricing plan was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render  "edit" }
        format.xml  { render :xml => @pricing_plan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pricing_plans/1
  # DELETE /pricing_plans/1.xml

  def destroy
    find_pricing_plan
    @pricing_plan.destroy
    respond_to do |format|
      format.html { redirect_to(admin_pricing_plans_url,:notice=>"Pricing plan was successfully destroyed") }
      format.xml  { head :ok }
    end
  end

  def find_pricing_plan
    @pricing_plan = Spree::PricingPlan.find(params[:id])
  end
end

app/helpers/spree/pricing_plans_helper.rb
module Spree
  module PricingPlansHelper
  end
end

app/views/spree/admin/pricing_plans/_form.html.erb
<%- locals = {:f => f} %>
<b><%= t("plan_name") %> </b><br />
<%= f.text_field :plan_name %><br />
<b><%= t("amount") %> </b><br />
    <%= f.text_field :amount %><br />
<b><%= t("transaction_fee") %> </b><br />
    <%= f.text_field :transaction_fee %><br />
<b><%= t("no_of_products") %> </b><br />
    <%= f.text_field :no_of_products %><br />

<b><%= t("payment_period") %> </b><br />
    <%= f.select:payment_period,%w{Monthly Weekly}%><br/>

<b><%= t("is_active") %> </b><br />
    <%= f.check_box :is_active %><br />

app/views/spree/admin/pricing_plans/edit.html.erb
<%= render 'spree/shared/error_messages', :target => @pricing_plan %>
<h1>Editing Plan</h1>

<%= form_for @pricing_plan, :url=>{:controller=>:pricing_plans,:action=>:update} do |f| %>
    <%= render :partial => "form", :locals => { :f => f } %>
    <%= render :partial => "spree/admin/shared/edit_resource_links" %>
<% end %>


<%= link_to 'Show', admin_pricing_plan_path(@pricing_plan) %> |
<%= link_to 'Back', admin_pricing_plans_path %>

app/views/spree/admin/pricing_plans/index.html.erb
<div class='toolbar'>
  <ul class='actions'>
    <li>
      <p><%= button_link_to t("new_plan"), new_admin_pricing_plan_path, :icon => 'add', :id => 'admin_new_pricing_plan_link' %></p>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%= t("listing_plans") %></h1>

<table class="index" id='listing_plans'>

  <thead>
  <tr>
	<div data-hook="admin_plans_index_headers">

      <th><%= sort_link @search,:plan_name,t("plan") %></th>
      <th><%= sort_link @search,:amount,t("amount") %></th>
      <th><%= sort_link @search,:transaction_fee,t("transaction_fee") %></th>
      <th><%= sort_link @search,:no_of_products,t("no_of_products") %></th>
      <th><%= t("payment_period") %></th>
      <th><%= t("payment_status") %></th>
      <th>
				<div data-hook="admin_plans_index_header_actions"></div>
<th>
				<div data-hook="admin_plans_index_header_actions"></div>
      </th>
      </th>
</div>
</tr>
  </thead>
  <tbody>
<% @pricing_plans.each do |pricing_plan| %>
   <%- locals = {:pricing_plan => pricing_plan} %>

  <tr id="pricing_plan_<%=pricing_plan.id%>">
    <td class='user_email'><%=link_to pricing_plan.plan_name, :action=>"edit",:id=>pricing_plan.id  %></td>
    <td><%= number_to_currency pricing_plan.amount %></td>
    <td><%= pricing_plan.transaction_fee %> %</td>
    <td><%= pricing_plan.no_of_products %></td>
    <td><%= pricing_plan.payment_period %></td>
    <td><%= (pricing_plan.is_active?) ? "Active" : "Inactive" %></td>

		<td>
        <%= link_to "edit",:action=>"edit",:id=>pricing_plan.id %> &nbsp;
        <td>
        <%= link_to "delete",admin_pricing_plan_path(pricing_plan),:method=>"delete" %> &nbsp;
		
		</td>
		</td>
		
  </tr>
<% end %>

</tbody>
</table>

app/views/spree/admin/pricing_plans/new.html.erb
<%= render 'spree/shared/error_messages', :target => @pricing_plan %>
<h1>New Plan</h1>

<%= form_for @pricing_plan, :url=>{:controller=>"pricing_plans",:action=>:create} do |f| %>
    <%= render :partial => "form", :locals => { :f => f } %>
    <%= render :partial => "spree/admin/shared/new_resource_links" %>

<%end%>

<%= link_to 'Back', admin_pricing_plans_path %>

app/views/spree/admin/pricing_plans/show.html.erb
<p>
  <b>Plan name:</b>
  <%= @pricing_plan.plan_name %>
</p>

<p>
  <b>Amount:</b>
  <%= number_to_currency @pricing_plan.amount %>
</p>

<p>
  <b>Transaction fee:</b>
  <%= @pricing_plan.transaction_fee %>
</p>

<p>
  <b>No of products:</b>
  <%= @pricing_plan.no_of_products %>
</p>

<p>
  <b>Payment period:</b>
  <%= @pricing_plan.payment_period %>
</p>

<p>
  <b>Status:</b>
  <%= @pricing_plan.is_active? ? "Active" : "Inactive" %>
</p>


<%= link_to_edit @pricing_plan, :class => "edit" %>  |
<%= link_to 'Back', admin_pricing_plans_path %>